a=("pen","pencil","book","mobile phone","laptop","tablet")
print(a)
print(type(a))
print(len(a))
print(a[5])
print(a[-4])
print(a[1:4])
print(a[-5:-2])
print(a[4:])
print(a[-4:])
print(a[:2])
print(a[:-3])
print("headphone" in a)
print("headphone" not in a)
for i in a:
    print(i)
b=list(a)
print(b)
b[4]="textbook"
print(b)
b.append("printer")
print(b)
b.insert(4,"black pen")
print(b)
del b[4]
print(b)
a=tuple(b)
print(a)
print(a.count("pen"))
print(a*2)
c=("ruler","box","bag","diary")
print(c)
print(a+c)