# m=open("file001.txt","x")
# n=open("file002.txt","x")
# p=open("file0003.txt","x")
m=open("file001.txt","w")
m.write("good mrng")
m.close()
n=open("file002.txt","w")
n.write("have a nice day")
n.close()
m=open("file001.txt","r")
c=m.read()
m.close()
n=open("file002.txt","r")
d=n.read()
n.close()
q=open("file003.txt","w")
q.write(c)
q.write("\n")
q.write(d)
q.close()