h="learn from yesterday, live for today"
print(h)
print(type(h))
print(len(h))
print(h[28:30])
print(h[-32:])
print(h[:17])
print(h[15:])
print("back" in h)
print(" " in h)
print("=" in h)
print("modification" not in h)
for g in h:
    print(g)
print("," in h)
print("," not in h)
print(h[12:])
print(h[15])
print(h[3])
print(h[0:9])
print(len(h))