x="python is a programming language"
print(x)
print(type(x))
print(len(x))
print(x[7])
print(x[5:12])
print(x[14:])
print(x[:4])    
print(x[-1])
print(x[-11:-6])
print(x[-8:])
print(x[:-3])
for i in x:
    print(i)
print("is" in x)
print("are" in x)
print("is" not in x)
print("are" not in x)
print("am" in x)
print(x.upper())
print(x.lower())
y="        hello"
print(y)
print(y.strip())
print(x.replace("python","java"))
print(x.split(" "))
print(x.count("a"))
