x=("blue","pink","black","red","skyblue")
print(x)
print(type(x))
print(len(x))
print(x[4])
print(x[1:3])
print(x[2:])
print(x[:4])
print(x[-4])
print(x[-5:-3])
print(x[:-5])
print("berry" in x)
print("berry" not in x)
for i in x:
    print(i)
y=list(x)
print(y)
y[4]="white"
print(y)
y.append("skyblue")
print(y)
y.insert(3,"rose")
print(y)
del y[2]
print(y)
x=tuple(y)
print(x.count("blue"))
print(x*3)
z=("red","pink","blue")
print(z)
print(x+z)
